const Access_key = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4MGIzNGIzMTljYjQyNmE0MWJiMjdkMzFlY2ZkYTZiMyIsInN1YiI6IjY1MjViMTZhZWE4NGM3MDBjYTBlMGViYiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.v732c8TiE44Rw0UPWX9qrbooUEtLR8hgb5OHClrb8Jk';

export default Access_key;